require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactNativeTemplateBlank' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNativeTemplateBlankTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    # Remove IPHONEOS_DEPLOYMENT_TARGET setting
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  
    flipper_post_install(installer)
  end
end

target 'ReactNativeTemplateBlank-tvOS' do
  # Pods for ReactNativeTemplateBlank-tvOS

  target 'ReactNativeTemplateBlank-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
