require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactNativeTemplateBlankTypescript' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNativeTemplateBlankTypescriptTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ReactNativeTemplateBlankTypescript-tvOS' do
  # Pods for ReactNativeTemplateBlankTypescript-tvOS

  target 'ReactNativeTemplateBlankTypescript-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Remove IPHONEOS_DEPLOYMENT_TARGET setting
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end